---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kdahi.
--- DateTime: 2022-04-09 9:29 a.m.
---


-- Create audio clip
local audio_clip = audio_clip(".\\src\\audio\\Joyride.wav", true)

print(audio_clip)

print("Audio channel :", audio_clip.channel)

print("Audio samples :", audio_clip.samples)

print("Audio sample rate HZ : ", audio_clip.sample_rate)

print("Audio frame length : ", audio_clip.frame_length)

print("Audio clip", "seconds : ", audio_clip.duration["seconds"], "\nmilliseconds : ", audio_clip.duration["milliseconds"], "\nmicroseconds : ", audio_clip.duration["microseconds"])

print("Audio clip first buffer data : ", audio_clip.buffer[1])

print("Audio clip buffer index : ", audio_clip[1])

print("Audio clip to standard : ", audio_clip:standard())

print("Audio clip to ambisonic : ", audio_clip:ambisonic())

print("Audio clip buffer length : ", #audio_clip)

