---
--- Generated by Luanalysis
--- Created by kdahi.
--- DateTime: 2022-04-24 1:57 PM
---

local listener = audio_listener(2);

print("left ear x :",listener.left_ear[1])
print("left ear y :", listener.left_ear[2])
print("left ear z :",listener.left_ear[3])

listener.left_ear = {2.0, 3.0, 4.0}

print("modified left ear x :",listener.left_ear[1])
print("modified left ear y :", listener.left_ear[2])
print("modified left ear z :",listener.left_ear[3])


print("right ear x :", listener.right_ear[1])
print("right ear y :", listener.right_ear[2])
print("right ear z :", listener.right_ear[3])

listener.right_ear = {-4, 1.5, 2.3}

print("modified right ear x :", listener.right_ear[1])
print("modified right ear y :", listener.right_ear[2])
print("modified right ear z :", listener.right_ear[3])

print("this is a ", listener)