---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Typic.
--- DateTime: 2022-05-01 3:49 PM
---


local raw_clip = raw_audio_clip(".\\src\\audio\\epic.mp3", true);

local audio_source = audio_source();

