[package]
name = "basic_obj_loader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
image = "*"
winit = "*"
cgmath = "*"
env_logger = "*"
log = "*"
wgpu = "0.8"
futures = "*"
bytemuck = {version = "*", features = ["derive"]}
tobj = "*"
anyhow = "*"
rayon = "1.4"