---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kdahi.
--- DateTime: 2022-03-30 6:42 p.m.
---
---
---
print(coroutine.status(add_10000))

print(coroutine.resume(add_10000, 6))

print(coroutine.status(add_10000))

