[package]
name = "fabled_obj"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = {version ="3.2.0", features = ["merging", "reordering", "async"]}
bitflags = {version = "1.2.1"}
