[package]
name = "fabled_transform"
version = "0.1.0"
edition = "2018"

[dependencies]
fabled_component = {path ="../fabled_component", version = "*"}
fabled_math = {path = "../fabled_math", version = "*"}
