[package]
name = "fabled_fbx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fbxcel = { version = "0.7.0", features = ["tree", "writer"] }
fbxcel-dom = "0.0.6"
rayon = {version = "1.5.1" }