[package]
name = "fabled_audio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.29"
rodio = {version = "0.14.0", features = ["default"]}
cpal = {version = "0.13.4"}
ambisonic = {version = "0.4.1" }
hrtf = {version = "0.7.0"}

parking_lot = "0.11.2"
# dsp-chain > 0.12 will result in a error. Missing to_sample()
#dsp-chain = {version = "0.12"}