[package]
name = "fabled_audio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = {version = "0.14.0", features = ["default"]}
cpal = {version = "0.13.4"}
#dsp-chain = {version = "0.13.1"}