[package]
name = "fabled_binding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = {version = "*", features = ["lua54", "vendored", "async"]}
thiserror = "1.0.30"
anyhow = "1.0.56"