name: Fabled_Engine

on:
  push:
    branches:
      - main
      - render
  pull_request:
    branches:
      - main
      - render

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
