#                \||/
#                |  @___oo
#      /\  /\   / (__,,,,| (Deployment)
#     ) /^\) ^\/ _)
#     )   /^\/   _)
#     )   _ /  / _)
# /\  )/\/ ||  | )_)
#<  >      |(,,) )__)
# ||      /    \)___)\
# | \____(      )___) )___
#  \______(_______;;; __;;;

name: Fabled-Engine 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --verbose
    - name: Format
      run: cargo fmt --all -- --check
    - name: Run tests
      run: cargo test --all --verbose
