name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '22 3 * * *'

jobs:
  stale:

    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'D-No issue activity'
        stale-pr-label: 'D-No pr activity'
